# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_auto_20161110_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
