# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
                ('altitud', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(max_length=200)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vuelo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Zona'),
        ),
        migrations.AddField(
            model_name='datavuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.Vuelo'),
        ),
    ]
