# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_vuelo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
